-- Шаг 1: удаляем битые записи (имена из одних знаков ?)
delete from public.warehouses
where is_system = true
  and name ~ '^[?\s\-]+$';

-- Шаг 2: вставляем все склады из WB API + международные
-- ON CONFLICT DO NOTHING — не трогает уже корректные записи
insert into public.warehouses (account_id, name, is_system) values
  (null, 'Белые Столбы',                                true),
  (null, 'Белые Столбы: Горючее',                       true),
  (null, 'Владивосток СГТ',                             true),
  (null, 'Владимир Воршинское',                         true),
  (null, 'Волгоград',                                   true),
  (null, 'Волгоград: Питание',                          true),
  (null, 'Воронеж',                                     true),
  (null, 'Воронеж СГТ',                                 true),
  (null, 'Воронеж: Питание',                            true),
  (null, 'Голицыно СГТ',                                true),
  (null, 'Домодедово 2: Питание',                       true),
  (null, 'Домодедово-2',                                true),
  (null, 'Домодедово-2 СГТ',                            true),
  (null, 'Екатеринбург (Перспективная): Питание',       true),
  (null, 'Екатеринбург - Перспективная 14',             true),
  (null, 'Екатеринбург СГТ',                            true),
  (null, 'Казань',                                      true),
  (null, 'Казань СГТ',                                  true),
  (null, 'Казань: Питание',                             true),
  (null, 'Климовск СГТ',                                true),
  (null, 'Коледино',                                    true),
  (null, 'Коледино: Горючее',                           true),
  (null, 'Котовск',                                     true),
  (null, 'Котовск: Питание',                            true),
  (null, 'Краснодар (Тихорецкая)',                      true),
  (null, 'Краснодар (Тихорецкая): Питание',             true),
  (null, 'Краснодар СГТ',                               true),
  (null, 'Красный Бор СГТ',                             true),
  (null, 'Кузнецк СГТ',                                 true),
  (null, 'Невинномысск',                                true),
  (null, 'Нижний Тагил Восточное',                      true),
  (null, 'Нижний Тагил: Индустриальная СГТ',            true),
  (null, 'Никольское СГТ',                              true),
  (null, 'Новосемейкино',                               true),
  (null, 'Новосемейкино: Питание',                      true),
  (null, 'Новосибирск СГТ',                             true),
  (null, 'Обухово',                                     true),
  (null, 'Обухово СГТ',                                 true),
  (null, 'Пенза',                                       true),
  (null, 'Пенза СГТ',                                   true),
  (null, 'Пермь: Горючее',                              true),
  (null, 'Подольск',                                    true),
  (null, 'Подольск 3',                                  true),
  (null, 'Подольск 3 СГТ',                              true),
  (null, 'Подольск 4',                                  true),
  (null, 'Радумля СГТ',                                 true),
  (null, 'Рязань (Тюшевское)',                          true),
  (null, 'Рязань (Тюшевское): Питание',                 true),
  (null, 'СЦ Абакан 2',                                 true),
  (null, 'СЦ Артем',                                    true),
  (null, 'СЦ Архангельск (ул Ленина)',                  true),
  (null, 'СЦ Астрахань',                                true),
  (null, 'СЦ Астрахань (Солянка)',                      true),
  (null, 'СЦ Барнаул',                                  true),
  (null, 'СЦ Белая Дача',                               true),
  (null, 'СЦ Белогорск',                                true),
  (null, 'СЦ Владикавказ',                              true),
  (null, 'СЦ Владимир',                                 true),
  (null, 'СЦ Внуково',                                  true),
  (null, 'СЦ Вологда 2',                                true),
  (null, 'СЦ Ереван',                                   true),
  (null, 'СЦ Иваново',                                  true),
  (null, 'СЦ Ижевск',                                   true),
  (null, 'СЦ Иркутск',                                  true),
  (null, 'СЦ Калуга',                                   true),
  (null, 'СЦ Кемерово',                                 true),
  (null, 'СЦ Киров',                                    true),
  (null, 'СЦ Крыловская',                               true),
  (null, 'СЦ Кузнецк',                                  true),
  (null, 'СЦ Курск',                                    true),
  (null, 'СЦ Липецк',                                   true),
  (null, 'СЦ Махачкала',                                true),
  (null, 'СЦ Махачкала Сепараторная',                   true),
  (null, 'СЦ Мурманск',                                 true),
  (null, 'СЦ Набережные Челны',                         true),
  (null, 'СЦ Нижний Новгород Ларина',                   true),
  (null, 'СЦ Нижний Тагил',                             true),
  (null, 'СЦ Новокузнецк',                              true),
  (null, 'СЦ Новосибирск 4',                            true),
  (null, 'СЦ Новосибирск Докучаева',                    true),
  (null, 'СЦ Обухово 2',                                true),
  (null, 'СЦ Омск',                                     true),
  (null, 'СЦ Оренбург Центральная',                     true),
  (null, 'СЦ Смоленск 3',                               true),
  (null, 'СЦ Софьино',                                  true),
  (null, 'СЦ Тамбов',                                   true),
  (null, 'СЦ Тверь',                                    true),
  (null, 'СЦ Томск',                                    true),
  (null, 'СЦ Ульяновск',                                true),
  (null, 'СЦ Хабаровск',                                true),
  (null, 'СЦ Челябинск 2',                              true),
  (null, 'СЦ Шушары',                                   true),
  (null, 'СЦ Ярославль Громова',                        true),
  (null, 'Санкт-Петербург (Уткина Заводь)',              true),
  (null, 'Санкт-Петербург СГТ',                         true),
  (null, 'Сарапул',                                     true),
  (null, 'Склад Владивосток',                           true),
  (null, 'Склад Домодедово Шинный',                     true),
  (null, 'Склад Ереван',                                true),
  (null, 'Склад Истра',                                 true),
  (null, 'Склад Шушары',                                true),
  (null, 'Софрино СГТ',                                 true),
  (null, 'Софьино СГТ',                                 true),
  (null, 'Сц Брянск 2',                                 true),
  (null, 'Тверь',                                       true),
  (null, 'Тверь СГТ',                                   true),
  (null, 'Тула',                                        true),
  (null, 'Чашниково',                                   true),
  (null, 'Чашниково СГТ',                               true),
  (null, 'Чашниково: Горючее',                          true),
  (null, 'Челябинск СГТ',                               true),
  (null, 'Чехов 1, Новоселки вл 11 стр 2',              true),
  (null, 'Чехов 2, Новоселки вл 11 стр 7',              true),
  (null, 'Шушары: Питание',                             true),
  (null, 'Щеглово (Холмогоры) СГТ',                     true),
  (null, 'Щербинка: Горючее',                           true),
  (null, 'Электросталь',                                true),
  (null, 'Электросталь: Питание',                       true),
  (null, 'Юрга',                                        true),
  (null, 'Ярославль СГТ',                               true),
  -- Международные (не в WB API, но нужны)
  (null, 'Алматы',                                      true),
  (null, 'Астана',                                      true),
  (null, 'Бишкек',                                      true),
  (null, 'Минск',                                       true),
  (null, 'Ташкент',                                     true)
on conflict do nothing;
