begin;
do $$
declare u uuid:=gen_random_uuid(); stranger uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); challenge uuid:=gen_random_uuid(); q jsonb; job uuid; n integer; reservation jsonb; request uuid:=gen_random_uuid();
begin
 insert into auth.users(id,email,email_confirmed_at) values(u,u||'@example.invalid',now()),(stranger,stranger||'@example.invalid',now());
 insert into public.accounts(id,name,plan,plan_until) values(a,'Rollback mail','seller',now()+interval '1 month');
 insert into public.account_members(account_id,user_id,role) values(a,u,'owner');
 perform set_config('request.jwt.claim.sub',stranger::text,true);
 set local role authenticated;
 if (public.get_brand_mail_settings(a)->>'allowed')::boolean then raise exception 'stranger read settings'; end if;
 begin perform public.set_brand_mail_fallback(a,true);raise exception 'stranger changed consent';exception when raise_exception then if sqlerrm<>'Нет права управления почтой бренда' then raise;end if;end;
 reset role;
 perform set_config('request.jwt.claim.sub',u::text,true);
 set local role authenticated;
 perform public.set_brand_mail_fallback(a,true);
 perform public.set_mail_preferences(true,false);
 reset role;
 perform set_config('request.jwt.claim.role','service_role',true);
 q:=public.begin_brand_mail_verification(a,u,' First@Example.invalid ',challenge,repeat('a',64));
 if q->>'email'<>'first@example.invalid' then raise exception 'normalization';end if;
 for n in 1..5 loop q:=public.verify_brand_mail(a,u,challenge,repeat('b',64));if (q->>'ok')::boolean then raise exception 'bad code accepted';end if;end loop;
 q:=public.verify_brand_mail(a,u,challenge,repeat('a',64));if (q->>'ok')::boolean then raise exception 'attempt cap bypass';end if;
 update public.company_brand_mail set requested_at=now()-interval '61 seconds' where account_id=a;
 challenge:=gen_random_uuid();perform public.begin_brand_mail_verification(a,u,'first@example.invalid',challenge,repeat('a',64));
 q:=public.verify_brand_mail(a,u,challenge,repeat('a',64));if not (q->>'ok')::boolean then raise exception 'valid code failed';end if;
 if not exists(select 1 from auth.users where id=u and email=u||'@example.invalid') then raise exception 'Auth email changed';end if;
 update public.company_brand_mail set requested_at=now()-interval '61 seconds' where account_id=a;
 challenge:=gen_random_uuid();perform public.begin_brand_mail_verification(a,u,'next@example.invalid',challenge,repeat('a',64));
 if not exists(select 1 from public.company_brand_mail where account_id=a and email='first@example.invalid') then raise exception 'unverified replacement applied';end if;
 begin perform public.begin_brand_mail_verification(a,u,'next@example.invalid',gen_random_uuid(),repeat('a',64));raise exception 'cooldown bypass';exception when raise_exception then if sqlerrm<>'Повторная отправка доступна через минуту' then raise;end if;end;
 job:=public.enqueue_numbered_mail('test:'||a,a,u,'campaign','News','Text');if job is not null then raise exception 'campaign without consent';end if;
 insert into public.batch_notifications(account_id,type,title,body,recipient_user_id) values(a,'test','Private title','Private body',u);
 select count(*) into n from public.numbered_mail_queue where account_id=a;if n<>1 then raise exception 'notification not queued';end if;
 q:=public.claim_numbered_mail();if jsonb_array_length(q)<>1 then raise exception 'claim count';end if;
 if q->0->>'message' like '%Private%' then raise exception 'notification data leaked';end if;
 if jsonb_array_length(public.claim_numbered_mail())<>0 then raise exception 'lease ignored';end if;
 perform public.finish_numbered_mail((q->0->>'id')::uuid,(q->0->>'lease')::uuid,true);
 update public.accounts set logo_subscription_until=now()+interval '1 month' where id=a;
 update public.company_brand_mail set fallback_allowed=false where account_id=a;
 reservation:=public.reserve_email_delivery_number(u||'@example.invalid',request,'invite');
 update public.email_delivery_requests set brand_account_id=a where request_id=request;
 q:=public.resolve_auth_mail_route(u||'@example.invalid',reservation->>'number',reservation->>'requested_at');
 if (q->>'allowed')::boolean then raise exception 'Auth fallback ignored consent';end if;
 if has_function_privilege('authenticated','public.verify_brand_mail(uuid,uuid,uuid,text)','EXECUTE') or has_function_privilege('anon','public.claim_numbered_mail()','EXECUTE') then raise exception 'private mail RPC exposed';end if;
 job:=public.enqueue_numbered_mail('blocked:'||a,a,u,'notification','Notice','Text');
 q:=public.claim_numbered_mail();if jsonb_array_length(q)<>0 then raise exception 'brand fallback without consent';end if;
 if not exists(select 1 from public.numbered_mail_queue where id=job and status='blocked') then raise exception 'missing block';end if;
 update public.company_brand_mail set fallback_allowed=true where account_id=a;
 q:=public.resolve_auth_mail_route(u||'@example.invalid',reservation->>'number',reservation->>'requested_at');
 if not (q->>'allowed')::boolean or q->>'reply_to'<>'first@example.invalid' then raise exception 'Auth verified reply route';end if;
 update public.numbered_mail_queue set available_at=now() where id=job;
 q:=public.claim_numbered_mail();if q->0->>'reply_to'<>'first@example.invalid' then raise exception 'verified Reply-To missing';end if;
 perform public.finish_numbered_mail((q->0->>'id')::uuid,(q->0->>'lease')::uuid,false);
 update public.mail_preferences set notifications=false where user_id=u;
 update public.numbered_mail_queue set available_at=now() where id=job;
 q:=public.claim_numbered_mail();if jsonb_array_length(q)<>0 then raise exception 'unsubscribe ignored';end if;
end $$;
rollback;
