-- All fixtures roll back; no external delivery.
begin;
do $$
declare u uuid:=gen_random_uuid(); actor uuid:=gen_random_uuid(); a uuid; e uuid; i uuid; t uuid:=gen_random_uuid(); s uuid; r record; q jsonb; n jsonb; req uuid; label text;
begin
 insert into auth.users(id,email,email_confirmed_at,created_at) values(u,u||'@example.invalid',now(),now()),(actor,actor||'@example.invalid',now(),now());
 insert into public.profiles(user_id,full_name,platform_role) values(actor,'Registry tester','superadmin') on conflict(user_id) do update set platform_role='superadmin';
 insert into public.accounts(name) values('Registry applicant') returning id into a;
 insert into public.accounts(name) values('Actual executor') returning id into e;
 insert into public.account_members(account_id,user_id,role) values(a,u,'owner'),(e,actor,'owner');
 insert into public.service_request_invites(token,executor_account_id,created_by,applicant_account_id,claimed_by) values(t,e,actor,a,u) returning id into i;
 insert into public.stores(account_id,name,marketplace,customer_account_id) values(e,'Registry store','wildberries',a) returning id into s;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 select * into r from public.admin_list_service_request_invites_v2() x where x.id=i;
 if r.state<>'bound_pending' or not r.email_confirmed or r.reserved_email<>u||'@example.invalid' or not r.is_available or r.auth_created_at is null or r.company_created_at is null then raise exception 'Pending/auth metadata wrong'; end if;
 q:=public.admin_preview_service_request_invite(t);
 if q->>'state'<>'bound_pending' or not (q->>'email_confirmed')::boolean then raise exception 'Preview mismatch';end if;
 if not (select has_company_request_link from public.get_account_stores_safe(e) x where x.id=s) then raise exception 'Active store link missing';end if;
 update public.service_request_invites set expires_at=now()-interval '1 second' where id=i;
 select * into r from public.admin_list_service_request_invites_v2() x where x.id=i;
 if r.state<>'expired' or r.is_available or r.ended_at is null or r.end_reason is null then raise exception 'Expiry state wrong';end if;
 if (select has_company_request_link from public.get_account_stores_safe(e) x where x.id=s) or exists(select 1 from public.get_customer_company_request_links(e) x where x.customer_account_id=a) then raise exception 'Expired URL exposed';end if;
 update public.service_request_invites set expires_at='infinity' where id=i;
 select * into r from public.admin_list_service_request_invites_v2() x where x.id=i;
 if r.state<>'bound' or not r.is_available then raise exception 'Permanent link wrong';end if;
 perform set_config('request.jwt.claim.role','service_role',true);
 n:=public.reserve_invite_email_number(u||'@example.invalid',gen_random_uuid(),'invite',t);
 if n->>'sender_name'<>'ELESTET' then raise exception 'Wrong sender';end if;
 update public.accounts set plan='seller',plan_until=now()+interval '1 month',logo_subscription_until=now()+interval '1 month' where id=e;
 if public.auth_sender_display_name(e) is not null then raise exception 'Unconnected branded sender advertised';end if;
 q:=public.resolve_auth_mail_route(u||'@example.invalid',n->>'number',n->>'requested_at');
 if (q->>'allowed')::boolean then raise exception 'Consent bypassed';end if;
 perform public.set_brand_mail_fallback(e,true);
 q:=public.resolve_auth_mail_route(u||'@example.invalid',n->>'number',n->>'requested_at');
 if not (q->>'allowed')::boolean or q->>'sender_name'<>'ELESTET' then raise exception 'Fallback sender wrong';end if;
 insert into public.service_requests(applicant_account_id,executor_account_id,title,created_by) values(a,e,'Private request',u) returning id into req;
 perform set_config('request.jwt.claim.sub',u::text,true);
 perform public.set_mail_preferences(true,false);
 insert into public.batch_notifications(account_id,type,title,body,recipient_user_id,source_request_id) values(a,'test','Secret title','Secret body',u,req);
 select format('C-%s · %s',short_id,name) into label from public.accounts where id=e;
 if not exists(select 1 from public.numbered_mail_queue where account_id=a and message like '%'||label||'%' and message not like '%Secret%') then raise exception 'Actual executor missing or confidential data leaked';end if;
 begin perform public.admin_list_service_request_invites_v2();raise exception 'FAIL regular user allowed';exception when insufficient_privilege then null;end;
 if has_function_privilege('anon','public.admin_list_service_request_invites_v2()','EXECUTE') then raise exception 'Anonymous registry grant';end if;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 update public.service_request_invites set revoked_at=now(),deleted_at=now(),delete_reason='replaced_by_applicant' where id=i;
 select * into r from public.admin_list_service_request_invites_v2() x where x.id=i;
 if r.state<>'replaced' or r.end_reason<>'Заменена другой ссылкой' or r.ended_at is null or r.is_available then raise exception 'Replacement mislabeled as deletion';end if;
 update public.service_request_invites set delete_reason='data_deleted_by_superadmin' where id=i;
 select * into r from public.admin_list_service_request_invites_v2() x where x.id=i;
 if r.state<>'deleted' or r.end_reason<>'Данные ссылки удалены администратором' then raise exception 'Deletion precedence';end if;
 update public.service_request_invites set delete_reason='expired' where id=i;
 select * into r from public.admin_list_service_request_invites_v2() x where x.id=i;
 if r.state<>'expired' or r.ended_at<>(select initial_expires_at from public.service_request_invites where id=i) then raise exception 'Cleanup expiry precedence';end if;
end $$;
rollback;
